# Nodeport service definition
apiVersion: v1
kind: Service
metadata:
  name: wazuh-sca-config-editor-service
spec:
  type: NodePort
  selector:
    app: wazuh-sca-config-editor
  ports:
    - name: http-api
      port: 3000
      nodePort: 31000
      targetPort: wazuh-sca-api
  externalIPs:
    - 192.168.0.250
